/**
 * src/core/export/MarkdownExporter.js
 *
 * Formats aggregated DB data into a structured Markdown document
 * designed to give an AI assistant maximum context for content creation.
 *
 * Document structure:
 *   1. Header           — export metadata (date, period, what's included)
 *   2. Voice & Rules    — tone, style, taboos; platform-specific rules
 *   3. Active Projects  — what you're currently building/promoting
 *   4. Posts            — your published posts (all platforms combined)
 *   5. Signals          — raw material: GitHub activity, notes, articles, etc.
 *   6. AI system prompt — ready-to-use instruction block
 */

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Format a Date to a readable string, or '—' if null/undefined. */
function fmtDate(d) {
  if (!d) return '—';
  return new Date(d).toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
}

/** Clamp a string to maxLen chars, appending '…' if truncated. */
function clamp(str, maxLen = 280) {
  if (!str) return '';
  const s = str.replace(/\n+/g, ' ').trim();
  return s.length <= maxLen ? s : s.slice(0, maxLen - 1) + '…';
}

/** Platform emoji for posts. */
const PLATFORM_EMOJI = {
  twitter:  '🐦',
  linkedin: '💼',
  telegram: '✈️',
  bluesky:  '🦋',
};

/** Render an engagement line for a post. */
function engagementLine(post) {
  const parts = [];
  if (post.likes   > 0) parts.push(`❤️ ${post.likes}`);
  if (post.reposts > 0) parts.push(`🔁 ${post.reposts}`);
  if (post.replies > 0) parts.push(`💬 ${post.replies}`);
  if (post.views   > 0) parts.push(`👁 ${post.views}`);
  return parts.length ? parts.join('  ') : 'no engagement data';
}

/** Signal type emoji. */
const SIGNAL_EMOJI = {
  release:       '🚀',
  commit_batch:  '📦',
  new_repo:      '🆕',
  readme_change: '📝',
  article:       '📰',
  note:          '💡',
  tool_review:   '🔧',
  news:          '📣',
};

/**
 * Priority order for signal types within a source group.
 * Lower index = rendered first.
 * Types not in this list are appended at the end in their natural order.
 */
const SIGNAL_TYPE_PRIORITY = [
  'release',
  'commit_batch',
  'new_repo',
  'readme_change',
];

/** Sort signal_type keys by the priority list, unknown types last. */
function sortSignalTypes(types) {
  return [...types].sort((a, b) => {
    const ai = SIGNAL_TYPE_PRIORITY.indexOf(a);
    const bi = SIGNAL_TYPE_PRIORITY.indexOf(b);
    // Both known → sort by priority index
    if (ai !== -1 && bi !== -1) return ai - bi;
    // Only a is known → a first
    if (ai !== -1) return -1;
    // Only b is known → b first
    if (bi !== -1) return 1;
    // Both unknown → alphabetical
    return a.localeCompare(b);
  });
}

const divider = () => '\n---\n';

// ─── Section renderers ────────────────────────────────────────────────────────

function renderHeader({ days, sections, generatedAt }) {
  const sectionLabels = {
    context:  'Voice & Rules',
    projects: 'Projects',
    posts:    'Posts',
    signals:  'Signals',
  };

  const included = sections
    .map(s => sectionLabels[s] ?? s)
    .join(', ');

  return [
    `# EANyra Content Export`,
    ``,
    `**Generated:** ${fmtDate(generatedAt)}`,
    `**Period:** last ${days} day${days !== 1 ? 's' : ''}`,
    `**Sections:** ${included}`,
    ``,
    `> This file was generated by EANyra for AI-assisted content creation.`,
  ].join('\n');
}

// ── Voice & Platform rules ────────────────────────────────────────────────────

function renderContext(context, requestedSections) {
  if (!requestedSections.includes('context')) return '';
  const parts = [];

  if (context.voice) {
    parts.push(`## 🎯 Your Voice & Style`);
    parts.push(``);
    const v = context.voice;

    if (v.tone) {
      parts.push(`**Tone:** ${v.tone}`);
      parts.push(``);
    }

    if (Array.isArray(v.likes) && v.likes.length) {
      parts.push(`**What works for you:**`);
      for (const item of v.likes) parts.push(`- ${item}`);
      parts.push(``);
    }

    if (Array.isArray(v.dislikes) && v.dislikes.length) {
      parts.push(`**What to avoid:**`);
      for (const item of v.dislikes) parts.push(`- ${item}`);
      parts.push(``);
    }

    if (Array.isArray(v.taboo) && v.taboo.length) {
      parts.push(`**Hard rules (never break):**`);
      for (const item of v.taboo) parts.push(`- ⛔ ${item}`);
      parts.push(``);
    }
  }

  if (context.platforms) {
    parts.push(`## 📐 Platform Rules`);
    parts.push(``);
    for (const [platform, rules] of Object.entries(context.platforms)) {
      const emoji = PLATFORM_EMOJI[platform] ?? '•';
      parts.push(`### ${emoji} ${platform.charAt(0).toUpperCase() + platform.slice(1)}`);
      if (rules.max_length) parts.push(`- **Max length:** ${rules.max_length} chars`);
      if (rules.language)   parts.push(`- **Language:** ${rules.language}`);
      if (rules.style)      parts.push(`- **Style:** ${rules.style}`);
      if (Array.isArray(rules.formats) && rules.formats.length) {
        parts.push(`- **Formats:** ${rules.formats.join(', ')}`);
      }
      if (rules.frequency)  parts.push(`- **Frequency:** ${rules.frequency}`);
      parts.push(``);
    }
  }

  if (context.bio) {
    parts.push(`## 👤 Bio (per platform)`);
    parts.push(``);
    for (const [platform, bio] of Object.entries(context.bio)) {
      parts.push(`**${platform}:** ${bio.short ?? bio}`);
    }
    parts.push(``);
  }

  return parts.join('\n');
}

// ── Active projects ───────────────────────────────────────────────────────────

function renderProjects(context, requestedSections) {
  if (!requestedSections.includes('projects')) return '';
  if (!Array.isArray(context.projects) || !context.projects.length) return '';

  const parts = [
    `## 📋 Active Projects`,
    ``,
    `> These are the projects you're currently building. Use them as content hooks.`,
    ``,
  ];

  for (const p of context.projects) {
    parts.push(`### ${p.name} (\`${p.slug}\`)`);
    parts.push(``);

    if (p.description) {
      parts.push(p.description.trim());
      parts.push(``);
    }

    if (Array.isArray(p.tech_stack) && p.tech_stack.length) {
      parts.push(`**Stack:** ${p.tech_stack.join(' · ')}`);
      parts.push(``);
    }

    if (p.links && Object.keys(p.links).length) {
      const linkStr = Object.entries(p.links)
        .map(([k, v]) => `[${k}](${v})`)
        .join(' · ');
      parts.push(`**Links:** ${linkStr}`);
      parts.push(``);
    }

    if (Array.isArray(p.content_angles) && p.content_angles.length) {
      parts.push(`**Content angles:**`);
      for (const angle of p.content_angles) parts.push(`- ${angle}`);
      parts.push(``);
    }

    if (Array.isArray(p.posting_rules) && p.posting_rules.length) {
      parts.push(`**Posting rules:**`);
      for (const rule of p.posting_rules) parts.push(`- ${rule}`);
      parts.push(``);
    }
  }

  return parts.join('\n');
}

// ── Posts ─────────────────────────────────────────────────────────────────────

function renderPosts(posts, requestedSections) {
  if (!requestedSections.includes('posts')) return '';

  const parts = [
    `## ✍️ Your Posts`,
    ``,
  ];

  if (!posts.length) {
    parts.push(`*No posts found for this period.*`);
    parts.push(``);
    return parts.join('\n');
  }

  const unused = posts.filter(p => !p.used);
  const used   = posts.filter(p => p.used);

  if (unused.length) {
    parts.push(`### New (not yet used for content)`);
    parts.push(``);

    // Group by platform for readability
    const byPlatform = groupBy(unused, p => p.platform);
    for (const [platform, platformPosts] of Object.entries(byPlatform)) {
      const emoji = PLATFORM_EMOJI[platform] ?? '•';
      parts.push(`#### ${emoji} ${platform.charAt(0).toUpperCase() + platform.slice(1)}`);
      parts.push(``);

      for (const p of platformPosts) {
        const link = p.raw_url ? `[→](${p.raw_url})` : '';
        parts.push(`**${fmtDate(p.posted_at)}** ${link}`);
        parts.push(``);
        parts.push(p.text.trim());
        parts.push(``);
        if (p.shared_url) parts.push(`🔗 ${p.shared_url}`);
        parts.push(`*${engagementLine(p)}*`);
        parts.push(``);
      }
    }
  }

  if (used.length) {
    parts.push(`### Already used ✅`);
    parts.push(``);
    for (const p of used) {
      const emoji = PLATFORM_EMOJI[p.platform] ?? '•';
      parts.push(`- ${emoji} **${fmtDate(p.posted_at)}** · ${clamp(p.text, 120)}`);
    }
    parts.push(``);
  }

  return parts.join('\n');
}

// ── Signals ───────────────────────────────────────────────────────────────────

function renderSignals(signals, requestedSections) {
  if (!requestedSections.includes('signals')) return '';

  const parts = [
    `## ⚡ Signals (Content Raw Material)`,
    ``,
    `> Use these as inspiration for posts — they are NOT ready content.`,
    ``,
  ];

  if (!signals.length) {
    parts.push(`*No signals found for this period.*`);
    parts.push(``);
    return parts.join('\n');
  }

  const unused = signals.filter(s => !s.used);
  const used   = signals.filter(s => s.used);

  if (unused.length) {
    // Group by source, then by signal_type with priority ordering
    const bySource = groupBy(unused, s => s.source);

    for (const [source, sourceSignals] of Object.entries(bySource)) {
      parts.push(`### ${source.charAt(0).toUpperCase() + source.slice(1)}`);
      parts.push(``);

      const byType      = groupBy(sourceSignals, s => s.signal_type);
      const sortedTypes = sortSignalTypes(Object.keys(byType));

      for (const type of sortedTypes) {
        const typeSignals = byType[type];
        const emoji = SIGNAL_EMOJI[type] ?? '•';
        const label = type.replace(/_/g, ' ');
        parts.push(`#### ${emoji} ${label.charAt(0).toUpperCase() + label.slice(1)}`);
        parts.push(``);

        for (const s of typeSignals) {
          if (type === 'commit_batch') {
            const meta = s.metadata ?? {};
            parts.push(`**${meta.repo ?? s.title}** — week ${meta.week ?? '?'}, ${meta.count ?? '?'} commits`);
            if (s.body) {
              const msgs = s.body.split('\n').filter(Boolean).slice(0, 5);
              for (const msg of msgs) parts.push(`  - ${msg}`);
            }
            if (s.url) parts.push(`  [View →](${s.url})`);
          } else {
            parts.push(`**${s.title}**`);
            parts.push(`*${fmtDate(s.occurred_at)}*`);
            if (s.body) parts.push(clamp(s.body, 300));
            if (s.url)  parts.push(`[View →](${s.url})`);
          }
          parts.push(``);
        }
      }
    }
  }

  if (used.length) {
    parts.push(`### Already used ✅`);
    parts.push(``);
    for (const s of used) {
      const emoji = SIGNAL_EMOJI[s.signal_type] ?? '•';
      parts.push(`- ${emoji} **${fmtDate(s.occurred_at)}** · ${clamp(s.title, 100)}`);
    }
    parts.push(``);
  }

  return parts.join('\n');
}

// ── AI system prompt ──────────────────────────────────────────────────────────

function renderSystemPrompt(context, requestedSections) {
  const platforms     = Object.keys(context.platforms ?? {});
  const voiceTone     = context.voice?.tone ?? 'direct and technical';
  const voiceLikes    = context.voice?.likes    ?? [];
  const voiceDislikes = context.voice?.dislikes ?? [];
  const voiceTaboo    = context.voice?.taboo    ?? [];
  const projects      = context.projects ?? [];

  // Build per-platform constraint lines from the platforms context
  const platformConstraints = platforms.map(p => {
    const r     = context.platforms[p] ?? {};
    const parts = [];
    if (r.max_length) parts.push(`max ${r.max_length} chars`);
    if (r.language)   parts.push(`language: ${r.language}`);
    if (r.style)      parts.push(r.style);
    return `  ${p.charAt(0).toUpperCase() + p.slice(1)}: ${parts.join(' · ')}`;
  });

  // Active project slugs with their angles as context anchors
  const projectBlocks = projects.map(p => {
    const angles = Array.isArray(p.content_angles) && p.content_angles.length
      ? `\n    Content angles: ${p.content_angles.join(' / ')}`
      : '';
    const rules = Array.isArray(p.posting_rules) && p.posting_rules.length
      ? `\n    Posting rules: ${p.posting_rules.join(' · ')}`
      : '';
    return `  ${p.name} (${p.slug})${angles}${rules}`;
  });

  const lines = [
    `## 🤖 System Prompt`,
    ``,
    `> Paste everything inside the code block into your AI chat at the start of a content session.`,
    ``,
    '```',
    `You are helping me plan and write social media content.`,
    `This file is your only context. Read it fully before suggesting anything.`,
    ``,
    `## My voice`,
    `Tone: ${voiceTone}`,
  ];

  if (voiceLikes.length) {
    lines.push(`What works: ${voiceLikes.join(' · ')}`);
  }
  if (voiceDislikes.length) {
    lines.push(`Avoid: ${voiceDislikes.join(' · ')}`);
  }
  if (voiceTaboo.length) {
    lines.push(`Hard rules — never break:`);
    for (const t of voiceTaboo) lines.push(`  - ${t}`);
  }

  if (platformConstraints.length) {
    lines.push(``, `## Platform constraints`);
    for (const c of platformConstraints) lines.push(c);
  }

  if (projectBlocks.length) {
    lines.push(``, `## Active projects`);
    for (const b of projectBlocks) lines.push(b);
  }

  lines.push(
    ``,
    `## How to use this file`,
    `- "Your Posts" section: shows what I've already published. Use it to understand my writing style and avoid repeating topics.`,
    `- "Already used" posts and signals: skip them — they've been covered.`,
    `- "Signals" section: raw material from GitHub activity and other sources. Turn these into post ideas — they are NOT ready content.`,
    `- For each session: suggest 3–5 concrete post drafts per platform. Each draft must follow the platform constraints above.`,
    ``,
    `## Workflow`,
    `When I say "help me with content" — scan the Signals section first, then look at recent Posts for style reference, then draft.`,
    `When I share a new export file — ignore all previous context and start fresh from the new file.`,
    `If a signal has no useful body text, tell me — don't fabricate details.`,
    `Never suggest generic tips or "best practices" — every post must be grounded in something concrete from this file.`,
    '```',
    ``,
  );

  return lines.join('\n');
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Group an array of objects by a key function.
 * @template T
 * @param {T[]} arr
 * @param {(item: T) => string} keyFn
 * @returns {Record<string, T[]>}
 */
function groupBy(arr, keyFn) {
  return arr.reduce((acc, item) => {
    const key = keyFn(item);
    (acc[key] ??= []).push(item);
    return acc;
  }, {});
}

// ─── Main export function ─────────────────────────────────────────────────────

/**
 * Build the full Markdown string from aggregated export data.
 *
 * @param {{
 *   context:     object,
 *   posts:       object[],
 *   signals:     object[],
 *   days:        number,
 *   sections:    string[],
 *   generatedAt: Date,
 * }} data
 * @returns {string}
 */
export function buildMarkdown(data) {
  const {
    context     = {},
    posts       = [],
    signals     = [],
    days        = 7,
    sections    = ['context', 'projects', 'posts', 'signals'],
    generatedAt = new Date(),
  } = data;

  const blocks = [
    renderHeader({ days, sections, generatedAt }),
    divider(),
    renderContext(context, sections),
    renderProjects(context, sections),
    sections.includes('posts')   ? divider() : '',
    renderPosts(posts, sections),
    sections.includes('signals') ? divider() : '',
    renderSignals(signals, sections),
    divider(),
    renderSystemPrompt(context, sections),
  ];

  return blocks.filter(Boolean).join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}