/**
 * src/core/export/MarkdownExporter.js
 *
 * Formats aggregated DB data into a structured Markdown document
 * designed to give an AI assistant maximum context for content creation.
 *
 * Document structure:
 *   1. Header           — export metadata (date, period, what's included)
 *   2. Voice & Rules    — tone, style, taboos; platform-specific rules
 *   3. Active Projects  — what you're currently building/promoting
 *   4. Twitter posts    — recent/unused tweets with engagement metrics
 *   5. LinkedIn posts   — recent/unused LinkedIn content
 *   6. GitHub activity  — releases, commits, new repos in the period
 *   7. AI system prompt — ready-to-use instruction block
 */

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Format a Date to a readable string, or '—' if null/undefined. */
function fmtDate(d) {
    if (!d) return '—';
    return new Date(d).toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  }
  
  /** Clamp a string to maxLen chars, appending '…' if truncated. */
  function clamp(str, maxLen = 280) {
    if (!str) return '';
    const s = str.replace(/\n+/g, ' ').trim();
    return s.length <= maxLen ? s : s.slice(0, maxLen - 1) + '…';
  }
  
  /** Render an engagement line for Twitter posts. */
  function twitterMeta(post) {
    const parts = [];
    if (post.likes    > 0) parts.push(`❤️ ${post.likes}`);
    if (post.retweets > 0) parts.push(`🔁 ${post.retweets}`);
    if (post.replies  > 0) parts.push(`💬 ${post.replies}`);
    if (post.views    > 0) parts.push(`👁 ${post.views}`);
    return parts.length ? parts.join('  ') : 'no engagement data';
  }
  
  /** Render a section divider. */
  const divider = () => '\n---\n';
  
  // ─── Section renderers ────────────────────────────────────────────────────────
  
  function renderHeader({ days, sections, generatedAt }) {
    const sectionLabels = {
      context:  'Voice & Rules',
      projects: 'Projects',
      twitter:  'Twitter',
      linkedin: 'LinkedIn',
      github:   'GitHub',
    };
  
    const included = sections
      .map(s => sectionLabels[s] ?? s)
      .join(', ');
  
    return [
      `# EANyra Content Export`,
      ``,
      `**Generated:** ${fmtDate(generatedAt)}`,
      `**Period:** last ${days} day${days !== 1 ? 's' : ''}`,
      `**Sections:** ${included}`,
      ``,
      `> This file was generated by EANyra for AI-assisted content creation.`,
      `> Posts marked ✅ were already used in a previous export.`,
    ].join('\n');
  }
  
  // ── Voice & Platform rules ────────────────────────────────────────────────────
  
  function renderContext(context, requestedSections) {
    const parts = [];
  
    if (requestedSections.includes('context') && context.voice) {
      parts.push(`## 🎯 Your Voice & Style`);
      parts.push(``);
  
      const v = context.voice;
  
      if (v.tone) {
        parts.push(`**Tone:** ${v.tone}`);
        parts.push(``);
      }
  
      if (Array.isArray(v.likes) && v.likes.length) {
        parts.push(`**What works for you:**`);
        for (const item of v.likes) parts.push(`- ${item}`);
        parts.push(``);
      }
  
      if (Array.isArray(v.dislikes) && v.dislikes.length) {
        parts.push(`**What to avoid:**`);
        for (const item of v.dislikes) parts.push(`- ${item}`);
        parts.push(``);
      }
  
      if (Array.isArray(v.taboo) && v.taboo.length) {
        parts.push(`**Hard rules (never break):**`);
        for (const item of v.taboo) parts.push(`- ⛔ ${item}`);
        parts.push(``);
      }
    }
  
    // Platform rules inline after voice so context stays together
    if (requestedSections.includes('context') && context.platforms) {
      parts.push(`## 📐 Platform Rules`);
      parts.push(``);
  
      const platforms = context.platforms;
      for (const [platform, rules] of Object.entries(platforms)) {
        parts.push(`### ${platform.charAt(0).toUpperCase() + platform.slice(1)}`);
        if (rules.max_length) parts.push(`- **Max length:** ${rules.max_length} chars`);
        if (rules.language)   parts.push(`- **Language:** ${rules.language}`);
        if (rules.style)      parts.push(`- **Style:** ${rules.style}`);
        if (rules.formats && Array.isArray(rules.formats)) {
          parts.push(`- **Formats:** ${rules.formats.join(', ')}`);
        }
        if (rules.frequency)  parts.push(`- **Frequency:** ${rules.frequency}`);
        parts.push(``);
      }
    }
  
    // Bio — compact, useful for ШІ to match the persona per platform
    if (requestedSections.includes('context') && context.bio) {
      parts.push(`## 👤 Bio (per platform)`);
      parts.push(``);
      for (const [platform, bio] of Object.entries(context.bio)) {
        parts.push(`**${platform}:** ${bio.short ?? bio}`);
      }
      parts.push(``);
    }
  
    return parts.join('\n');
  }
  
  // ── Active projects ───────────────────────────────────────────────────────────
  
  function renderProjects(context, requestedSections) {
    if (!requestedSections.includes('projects')) return '';
    if (!Array.isArray(context.projects) || !context.projects.length) return '';
  
    const parts = [
      `## 📋 Active Projects`,
      ``,
      `> These are the projects you're currently building. Use them as content hooks.`,
      ``,
    ];
  
    for (const p of context.projects) {
      parts.push(`### ${p.name} (\`${p.slug}\`)`);
      parts.push(``);
  
      if (p.description) {
        parts.push(p.description.trim());
        parts.push(``);
      }
  
      if (Array.isArray(p.tech_stack) && p.tech_stack.length) {
        parts.push(`**Stack:** ${p.tech_stack.join(' · ')}`);
        parts.push(``);
      }
  
      if (p.links && Object.keys(p.links).length) {
        const linkStr = Object.entries(p.links)
          .map(([k, v]) => `[${k}](${v})`)
          .join(' · ');
        parts.push(`**Links:** ${linkStr}`);
        parts.push(``);
      }
  
      if (Array.isArray(p.content_angles) && p.content_angles.length) {
        parts.push(`**Content angles (what to post about):**`);
        for (const angle of p.content_angles) parts.push(`- ${angle}`);
        parts.push(``);
      }
  
      if (Array.isArray(p.posting_rules) && p.posting_rules.length) {
        parts.push(`**Posting rules:**`);
        for (const rule of p.posting_rules) parts.push(`- ${rule}`);
        parts.push(``);
      }
    }
  
    return parts.join('\n');
  }
  
  // ── Twitter posts ─────────────────────────────────────────────────────────────
  
  function renderTwitter(posts, requestedSections) {
    if (!requestedSections.includes('twitter')) return '';
  
    const parts = [
      `## 🐦 Twitter — Recent Posts`,
      ``,
    ];
  
    if (!posts.length) {
      parts.push(`*No posts found for this period.*`);
      parts.push(``);
      return parts.join('\n');
    }
  
    const unused = posts.filter(p => !p.used);
    const used   = posts.filter(p => p.used);
  
    if (unused.length) {
      parts.push(`### New (not yet used for content)`);
      parts.push(``);
      for (const p of unused) {
        parts.push(`#### [@${p.username}](${p.raw_url ?? '#'}) · ${fmtDate(p.posted_at)}`);
        parts.push(``);
        parts.push(p.text.trim());
        parts.push(``);
        parts.push(`*${twitterMeta(p)}*`);
        parts.push(``);
      }
    }
  
    if (used.length) {
      parts.push(`### Already used ✅`);
      parts.push(``);
      for (const p of used) {
        parts.push(`- **${fmtDate(p.posted_at)}** · ${clamp(p.text, 120)} *(${twitterMeta(p)})*`);
      }
      parts.push(``);
    }
  
    return parts.join('\n');
  }
  
  // ── LinkedIn posts ────────────────────────────────────────────────────────────
  
  function renderLinkedin(posts, requestedSections) {
    if (!requestedSections.includes('linkedin')) return '';
  
    const parts = [
      `## 💼 LinkedIn — Recent Posts`,
      ``,
    ];
  
    if (!posts.length) {
      parts.push(`*No posts found for this period.*`);
      parts.push(``);
      return parts.join('\n');
    }
  
    const unused = posts.filter(p => !p.used);
    const used   = posts.filter(p => p.used);
  
    if (unused.length) {
      parts.push(`### New (not yet used for content)`);
      parts.push(``);
      for (const p of unused) {
        parts.push(`#### [${p.username}](${p.raw_url ?? '#'}) · ${fmtDate(p.posted_at)}`);
        parts.push(``);
        parts.push(p.text.trim());
        parts.push(``);
        if (p.shared_url) parts.push(`🔗 ${p.shared_url}`);
        parts.push(``);
      }
    }
  
    if (used.length) {
      parts.push(`### Already used ✅`);
      parts.push(``);
      for (const p of used) {
        parts.push(`- **${fmtDate(p.posted_at)}** · ${clamp(p.text, 120)}`);
      }
      parts.push(``);
    }
  
    return parts.join('\n');
  }
  
  // ── GitHub activity ───────────────────────────────────────────────────────────
  
  const GITHUB_EMOJI = {
    release:       '🚀',
    commit_batch:  '📦',
    new_repo:      '🆕',
    readme_change: '📝',
  };
  
  function renderGithub(events, requestedSections) {
    if (!requestedSections.includes('github')) return '';
  
    const parts = [
      `## ⚡ GitHub Activity`,
      ``,
    ];
  
    if (!events.length) {
      parts.push(`*No GitHub events found for this period.*`);
      parts.push(``);
      return parts.join('\n');
    }
  
    // Group by event_type for readability
    const byType = {};
    for (const ev of events) {
      (byType[ev.event_type] ??= []).push(ev);
    }
  
    const typeOrder = ['release', 'new_repo', 'readme_change', 'commit_batch'];
  
    for (const type of typeOrder) {
      if (!byType[type]?.length) continue;
  
      const emoji = GITHUB_EMOJI[type] ?? '•';
      const label = type.replace('_', ' ');
      parts.push(`### ${emoji} ${label.charAt(0).toUpperCase() + label.slice(1)}`);
      parts.push(``);
  
      for (const ev of byType[type]) {
        if (type === 'commit_batch') {
          const meta = ev.metadata ?? {};
          parts.push(`**${ev.username}/${ev.repo}** — week ${meta.week ?? '?'}, ${meta.count ?? '?'} commits`);
          if (ev.body) {
            const msgs = ev.body.split('\n').filter(Boolean).slice(0, 5);
            for (const msg of msgs) parts.push(`  - ${msg}`);
          }
          if (ev.url) parts.push(`  [View →](${ev.url})`);
        } else {
          parts.push(`**${ev.title}**`);
          parts.push(`*${ev.username}/${ev.repo} · ${fmtDate(ev.occurred_at)}*`);
          if (ev.body) parts.push(clamp(ev.body, 200));
          if (ev.url)  parts.push(`[View →](${ev.url})`);
        }
        parts.push(``);
      }
    }
  
    return parts.join('\n');
  }
  
  // ── AI system prompt ──────────────────────────────────────────────────────────
  
  function renderSystemPrompt(context, requestedSections) {
    const platformList = [];
    if (requestedSections.includes('twitter'))  platformList.push('Twitter/X');
    if (requestedSections.includes('linkedin')) platformList.push('LinkedIn');
  
    const projectNames = (context.projects ?? [])
      .map(p => p.name)
      .join(', ');
  
    const voiceTone = context.voice?.tone ?? 'direct and technical';
  
    return [
      `## 🤖 How to Use This File (System Prompt)`,
      ``,
      `> Copy this block into your AI chat before asking for content help.`,
      ``,
      `\`\`\``,
      `You are a content strategist helping me manage my social media presence.`,
      ``,
      `Use the data in this file as your only source of truth about:`,
      `- My tone and style (Voice & Style section)`,
      `- What I'm building (Active Projects section)`,
      `- What I've already posted (Twitter / LinkedIn sections)`,
      `- What happened in my code recently (GitHub Activity section)`,
      ``,
      `My tone: ${voiceTone}`,
      platformList.length
        ? `Target platforms: ${platformList.join(', ')}`
        : '',
      projectNames
        ? `Active projects: ${projectNames}`
        : '',
      ``,
      `Rules:`,
      `- Never repeat content I've already posted (marked ✅)`,
      `- Always follow the platform-specific rules in "Platform Rules"`,
      `- Base post ideas on real GitHub activity or project angles — not generic tips`,
      `- Respect the Hard Rules listed under Voice & Style`,
      `- Suggest 3–5 post drafts per platform, not one`,
      ``,
      `When I say "help me with content this week" — use this file.`,
      `When I share a new export — discard the previous one.`,
      `\`\`\``,
      ``,
    ].filter(line => line !== undefined).join('\n');
  }
  
  // ─── Main export function ─────────────────────────────────────────────────────
  
  /**
   * Build the full Markdown string from aggregated export data.
   *
   * @param {{
   *   context:       object,
   *   twitterPosts:  object[],
   *   linkedinPosts: object[],
   *   githubEvents:  object[],
   *   days:          number,
   *   sections:      string[],   // which sections to include
   *   generatedAt:   Date,
   * }} data
   * @returns {string}
   */
  export function buildMarkdown(data) {
    const {
      context       = {},
      twitterPosts  = [],
      linkedinPosts = [],
      githubEvents  = [],
      days          = 7,
      sections      = ['context', 'projects', 'twitter', 'linkedin', 'github'],
      generatedAt   = new Date(),
    } = data;
  
    const blocks = [
      renderHeader({ days, sections, generatedAt }),
      divider(),
      renderContext(context, sections),
      renderProjects(context, sections),
      sections.includes('twitter')  ? divider() : '',
      renderTwitter(twitterPosts, sections),
      sections.includes('linkedin') ? divider() : '',
      renderLinkedin(linkedinPosts, sections),
      sections.includes('github')   ? divider() : '',
      renderGithub(githubEvents, sections),
      divider(),
      renderSystemPrompt(context, sections),
    ];
  
    return blocks.filter(Boolean).join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
  }