import fs   from 'node:fs/promises';
import path  from 'node:path';
import { query, queryOne } from '../db.js';

/**
 * src/core/mcp/tools/context.js
 *
 * Tools:
 *   context_get  — voice, bio, platform rules, active projects
 *   export_get   — latest export Markdown file as a string
 */

// Project root: server.js is at src/core/mcp/server.js → 4 levels up
const PROJECT_ROOT = new URL('../../../../', import.meta.url).pathname;
const EXPORTS_DIR  = path.join(PROJECT_ROOT, 'data', 'exports');

export function buildContextTools() {
  return [...contextTools, ...exportTools];
}

// ── context_get ───────────────────────────────────────────────────────────────

const contextTools = [
  {
    name: 'context_get',
    description:
      'Returns the author\'s full context: tone/voice, bio per platform, ' +
      'content rules per platform, and active projects with content angles and posting rules. ' +
      'Always call this before generating or suggesting any post content.',
    inputSchema: {
      type: 'object',
      properties: {
        key: {
          type:        'string',
          description:
            'Return only a specific key: ' +
            '"voice", "bio", "platforms", or "project.<slug>". ' +
            'Omit to get the full context.',
        },
      },
    },
    async handler({ key } = {}) {
      if (key) {
        const row = await queryOne(
          'SELECT value FROM user_context WHERE key = ?',
          [key],
        );
        if (!row) {
          return {
            error: `Context key "${key}" not found. Run "eanyra context sync" to populate.`,
          };
        }
        return { key, value: tryParse(row.value, row.value) };
      }

      const rows = await query('SELECT key, value FROM user_context ORDER BY key');
      const ctx  = {};
      for (const row of rows) {
        if (row.key.startsWith('project.')) continue; // loaded from projects table below
        ctx[row.key] = tryParse(row.value, row.value);
      }

      const projects = await query(`
        SELECT slug, name, status, description,
               tech_stack, links, content_angles, posting_rules
        FROM   projects
        WHERE  status = 'active'
        ORDER  BY slug
      `);

      ctx.projects = projects.map(p => ({
        slug:           p.slug,
        name:           p.name,
        status:         p.status,
        description:    p.description,
        tech_stack:     tryParse(p.tech_stack,     []),
        links:          tryParse(p.links,          {}),
        content_angles: tryParse(p.content_angles, []),
        posting_rules:  tryParse(p.posting_rules,  []),
      }));

      return ctx;
    },
  },
];

// ── export_get ────────────────────────────────────────────────────────────────

const exportTools = [
  {
    name: 'export_get',
    description:
      'Return the latest export Markdown file from data/exports/ as a string. ' +
      'Export files are generated by "npm run export" and contain your voice, ' +
      'platform rules, active projects, recent posts, and pending signals — ' +
      'everything needed for a content session in one document. ' +
      'Use as a fast alternative to calling context_get + posts_get + signals_get separately.',
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type:        'string',
          description:
            'Specific filename to load, e.g. "export-2025-04-01.md". ' +
            'Omit to get the most recent file.',
        },
        max_chars: {
          type:        'integer',
          description: 'Truncate content to this many characters (default 80000).',
          default:     80_000,
        },
      },
    },
    async handler({ file, max_chars = 80_000 } = {}) {
      let files;
      try {
        const entries = await fs.readdir(EXPORTS_DIR);
        files = entries
          .filter(f => f.startsWith('export-') && f.endsWith('.md'))
          .sort()
          .reverse(); // newest first
      } catch {
        return {
          error:
            `Export directory not found: ${EXPORTS_DIR}. ` +
            'Run "npm run export" first.',
        };
      }

      if (!files.length) {
        return {
          error: 'No export files found in data/exports/. Run "npm run export" to generate one.',
        };
      }

      const target = file ? files.find(f => f === file) : files[0];

      if (!target) {
        return { error: `File "${file}" not found.`, available: files };
      }

      const filePath = path.join(EXPORTS_DIR, target);
      const stat     = await fs.stat(filePath);
      let content    = await fs.readFile(filePath, 'utf-8');

      const truncated = content.length > max_chars;
      if (truncated) {
        content = content.slice(0, max_chars) + '\n\n[… truncated — increase max_chars to see more]';
      }

      return {
        file:            target,
        generated_at:    stat.mtime.toISOString(),
        size_chars:      content.length,
        truncated,
        available_files: files,
        content,
      };
    },
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function tryParse(raw, fallback) {
  if (!raw) return fallback;
  try { return JSON.parse(raw); } catch { return fallback; }
}